# Generated by Django 5.2.12 on 2026-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.AddField(
            model_name='notes',
            name='like',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
